resources:
  repositories:
    - repository: facet
      type: github
      endpoint: https://github.com/konst-int-i/
      name: facet
      ref: develop



trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
- checkout: self
- checkout: facet


- script: dir $(Build.SourcesDirectory)

#version- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: |
#      eval "$(conda shell.bash hook)"
#      conda install -y conda-build
#      make package
#  displayName: "Build conda package"

- script: |
    pip install pytest pytest-azurepipelines
    pytest test/
  displayName: 'Run pytest'