name: gamma-common
channels:
  - conda-forge
dependencies:
  - black = 19.3
  - numpy = 1.16.*
  - pandas = 0.24.*
  - pip = 19.1
  - pytest = 4.4.*
  - pytest-cov = 2.6.*
  - python = 3.6
  - pip:
      - pre_commit == 1.16.*
