name: yield-engine
channels:
  - conda-forge
dependencies:
  - black = 19.3
  - joblib = 0.13.*
  - lightgbm = 2.2.*
  - matplotlib = 3.0.*
  - nbsphinx=0.4.*
  - numpy = 1.16.*
  - pandas = 0.24.*
  - pip = 19.1
  - pluggy = 0.11.*
  - pytest = 4.4.*
  - pytest-cov = 2.6.*
  - python = 3.6
  - pyyaml = 5.1.*
  - scikit-learn = 0.21.*
  - scipy = 1.2.*
  - shap = 0.28.*
  - sphinx-autodoc-typehints=1.6.*
  - sphinx=2.0.*
  - sphinx_rtd_theme=0.4.*
  - xlrd = 1.2.*
  - yaml = 0.1.*
  - pip:
      - pre_commit == 1.16.*
      - boruta == 0.3