name: gamma-viz
channels:
  - conda-forge
dependencies:
  - black = 19.3
  - matplotlib = 3.0.*
  - numpy = 1.16.*
  - pandas = 0.24.*
  - pip = 19.1
  - pluggy = 0.11.*
  - pytest = 4.4.*
  - pytest-cov = 2.6.*
  - python = 3.6
  - pyyaml = 5.1.*
  - sphinx-autodoc-typehints=1.6.*
  - sphinx=2.0.*
  - sphinx_rtd_theme=0.4.*
  - xlrd = 1.2.*
  - yaml = 0.1.*
  - pip:
      - pre_commit == 1.16.*
      - git+ssh://git@git.sourceai.io/alpha/gamma-common.git#egg=gamma.common