name: yield-engine
channels:
  - conda-forge
dependencies:
  - black = 19.3
  - joblib = 0.13.*
  - lightgbm = 2.2.*
  - pandas = 0.24.*
  - pip = 19.1
  - pluggy = 0.11.*
  - pytest = 4.4.*
  - pytest-cov = 2.6.*
  - python = 3.6
  - pyyaml = 5.1.*
  - scikit-learn = 0.21.*
  - shap = 0.28.*
  - xlrd = 1.2.0
  - pip:
      - pre_commit == 1.16.*