[tool.black]
# quiet = "True"
line-length = 88
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | data
    | docs
    | notebooks
    | sphinx
  )/
)
'''

[tool.isort]
profile = "black"
src_paths = ["src", "test"]
known_local_folder = ["pytools"]
known_first_party = []
known_third_party = [
    "numpy", "pandas", "joblib", "sklearn", "matplot"
]
